 
INSERT INTO TB_CLIENT (
			CLIENT_ENTITY_ID, CLIENT_ID, CLIENT_SECRET, CLIENT_NAME, ACCESS_TOKEN_VALIDITY_SEC, 
			REFRESH_TOKEN_VALIDITY_SEC, ID_TOKEN_VALIDITY_SEC, IS_DYNAMICALLY_REGISTERED, 
			IS_ALLOWED_INTROSECPTION, APPLICATION_TYPE, CLIENT_URI, AUTHENTICATION_TYPE, DEFAULT_MAX_AGE, DEVICE_CODE_VALIDITY_SEC)
VALUES ('1', 'client', '$2a$10$2khDhnZ0kqTf6KAII5F/YOO3ciuF2Z8hdbWaulymCnB5uB8gfHgyq', 'Test Client', 3600, -1, 600, 'N', 'Y', 'WEB', 'http://titan.sysbeanlocal.com:6580/login/oauth2/code/sysbean', 'SECRET_BASIC', 0, 0);


INSERT INTO TB_SYSTEM_SCOPE (
			SYSTEM_SCOPE_ID, SCOPE_VALUE, SCOPE_DESCRIPTION, SCOPE_ICON, DEFAULT_SCOPE, RESTRICTED_SCOPE)
VALUES ('1', 'openid', 'OpenID Connect Scope', '', 'Y', 'N');

INSERT INTO TB_SYSTEM_SCOPE (
			SYSTEM_SCOPE_ID, SCOPE_VALUE, SCOPE_DESCRIPTION, SCOPE_ICON, DEFAULT_SCOPE, RESTRICTED_SCOPE)
VALUES ('2', 'profile', 'Profile Scope', '', 'Y', 'N');

INSERT INTO TB_SYSTEM_SCOPE (
			SYSTEM_SCOPE_ID, SCOPE_VALUE, SCOPE_DESCRIPTION, SCOPE_ICON, DEFAULT_SCOPE, RESTRICTED_SCOPE)
VALUES ('3', 'offline_access', 'Refresh Token Scope', '', 'Y', 'N');

INSERT INTO TB_CLIENT_SCOPE (
			CLIENT_SCOPE_ID, SCOPE_VALUE, CLIENT_ENTITY, DEFAULT_SCOPE)
VALUES ('1', 'openid', '1', 'N');

INSERT INTO TB_CLIENT_SCOPE (
			CLIENT_SCOPE_ID, SCOPE_VALUE, CLIENT_ENTITY, DEFAULT_SCOPE)
VALUES ('2', 'profile', '1', 'N');

INSERT INTO TB_CLIENT_SCOPE (
			CLIENT_SCOPE_ID, SCOPE_VALUE, CLIENT_ENTITY, DEFAULT_SCOPE)
VALUES ('3', 'offline_access', '1', 'N');

INSERT INTO TB_CLIENT_REDIRECT (
			CLIENT_REDIRECT_ID, CLIENT_URI, CLIENT_ENTITY)
VALUES ('1', 'http://titan.sysbeanlocal.com:6580/login/oauth2/code/sysbean', '1');


INSERT INTO TB_CLIENT_GRANT_TYPE
			(CLIENT_GRANT_TYPE_ID, GRANT_TYPE, CLIENT_ENTITY)
VALUES ('1', 'AUTHORIZATION_CODE', '1');

INSERT INTO TB_CLIENT_GRANT_TYPE
			(CLIENT_GRANT_TYPE_ID, GRANT_TYPE, CLIENT_ENTITY)
VALUES ('2', 'IMPLICIT', '1');

INSERT INTO TB_CLIENT_GRANT_TYPE
			(CLIENT_GRANT_TYPE_ID, GRANT_TYPE, CLIENT_ENTITY)
VALUES ('3', 'REDELEGATE', '1');

INSERT INTO TB_CLIENT_GRANT_TYPE
			(CLIENT_GRANT_TYPE_ID, GRANT_TYPE, CLIENT_ENTITY)
VALUES ('4', 'REFRESH_TOKEN', '1');

INSERT INTO TB_CLIENT_GRANT_TYPE
(CLIENT_GRANT_TYPE_ID, GRANT_TYPE, CLIENT_ENTITY)
VALUES ('5', 'CLIENT_CREDENTIALS', '1');

INSERT INTO TB_SYSTEM_USER (USER_CODE, BIRTH_DATE, CREATED_ON, EMAIL_ID, EMAIL_VERIFIED, ENABLED, FAMILY_NAME, GENDER, GIVEN_NAME,
            LOCALE, MIDDLE_NAME, USER_NAME, NICK_NAME, PHONE_NUMBER, PHONE_VERIFIED, PICTURE, PREFERRED_USERNAME, PROFILE, SUB,
            UPDATED_ON, WEBSITE, ZONE_INFO)
VALUES ('1', NULL, NULL, 'bitanxen@gmail.com', 'Y', 'Y', 'Biswas', 'M', 'Bitan', 'en', '', 'admin', 'XEN', '96129813', 'Y', NULL, 'admin',
        '', 'admin', NULL, 'https://bitanxen.in', 'Asia/Singapore');



